### ISSUE TITLE
Remove txsocksx dependency using txtorcon TorSocksEndpoint

### ISSUE THREAD

**Issue by juga0** [meejah/carml#26]
``txsocksx`` is not needed anymore because ``txtorcon`` implements the socks endpoint and it's the only dependency that is preventing ``carml`` to be python 3 compatible.

Creating this issue so that we don't forget. I don't know if/when i could work on it.

**Comment by meejah** [comment]
removed

**Comment by juga0** [comment]
Nice, thanks!
Which would be the commit(s)?

**Comment by meejah** [comment]
Not *exactly* sure, but I merged a python3 upgrade branch "recently" and even-more-recently some updates to signatures and pinned dependencies..

**Comment by meejah** [comment]
https://github.com/meejah/carml/commit/5901ae84a9ac57de7f017f6b61481818cf4fae3d#diff-2eeaed663bd0d25b7e608891384b7298
