### ISSUE TITLE
Add support for full addresses to the temphs command

### ISSUE THREAD

**Issue by exarkun** [meejah/carml#28]
Tor's `HiddenServicePort` directive takes a remote port number and an _address_ - an IP and a port number.  This can be used to create a service backed by a server not on localhost.  `carml temphs` seems to only accept remote port number and a port number on localhost.

Extend `carml temphs` so it can specify a non-localhost "local" address for the service.

I'd suggest something like `carm temphs <remote port>[:<target address>]:<target port>` (and perhaps allow multiple such positional arguments to set up multiple services.

**Comment by exarkun** [comment]
Possibly this feature exists already but is not discoverable in the documentation.  Reading the implementation of the temphs command I found it uses the txtorcon API `create_onion_service` which in turn uses an internal API `_validate_ports`.  Reading that method's docstring suggests that a "port" like "remote a.b.c.d:local" might already work.  If so, this is really a documentation ticket, instead, to make this feature discoverable.

**Comment by meejah** [comment]
Okay, cool -- of note here, I've changed this to "carml onion" in the "post-python3" branch, which is probably the better place to fix/improve this (and yeah, no docs for it at all... :/ )

(carml will become python3-only after I merge the above; see also https://github.com/meejah/carml/pull/27)

**Comment by meejah** [comment]
This is in the latest release now.
