### ISSUE TITLE
[python 3.7.1] Invalid syntax 

### ISSUE THREAD

**Issue by rprimus** [meejah/carml#34]
Sun Dec 16 19:54:48 GMT 2018

FYI:

Just tried with `3.7.1` and got:
```
: ; carml
Traceback (most recent call last):
  File "/Users/rprimus/.pyenv/versions/3.7.1/bin/carml", line 7, in <module>
    from carml.cli import carml
  File "/Users/rprimus/.pyenv/versions/3.7.1/lib/python3.7/site-packages/carml/cli.py", line 556
    def relay(ctx, list, info, await, info_file):
                                   ^
SyntaxError: invalid syntax
```

Trying to track down what's the problem.

**Comment by rprimus** [comment]
Sun Dec 16 20:02:39 GMT 2018

Found it:

From https://docs.python.org/3.7/whatsnew/3.7.html:
```
Backwards incompatible syntax changes:

async and await are now reserved keywords.
```

**Comment by meejah** [comment]
Ah, yes that won't work .. simply re-naming the variable name should be sufficient. Thanks for the report!

**Comment by rprimus** [comment]
Sun Dec 16 20:34:24 GMT 2018

> simply re-naming the variable name should be sufficient

Aye - renaming in 3 places that function is sufficient.

**Comment by meejah** [comment]
Will gladly merge a PR if you have one handy ;)
