### ISSUE TITLE
fix setup.py dependencies + install instructions

### ISSUE THREAD

**Issue by meejah** [meejah/carml#7]
From alecmuffett in #tor-project:

 - Raspian
 - had to `apt-get install liblzma-dev`
 - for some reason had to manually pip-install twisted, service_identity, ipaddress and parsley

**Comment by alecmuffett** [comment]
On a fresh node:

---- run ----

aptitude install python-pip liblzma-dev

pip install --upgrade pip

pip install carml

---- errors during build ----

Compiling /tmp/pip-build-61DluM/carml/carml/click_autodoc.py ...
File "/tmp/pip-build-61DluM/carml/carml/click_autodoc.py", line 49
section = nodes.section()
^
SyntaxError: invalid syntax

---- errors on first run as non-root user ----

00:22:28 rig6:~ $ carml
Traceback (most recent call last):
File "/usr/local/bin/carml", line 7, in <module>
from carml.dispatch import dispatch
ImportError: No module named carml.dispatch

----- fixed permissions ----

---- errors on second run as non-root user ----

00:23:33 rig6:~ $ carml
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module and a recent enough pyOpenSSL \
to support it, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.

---- pip install service_identity && fix permissions again ----

Appears to work

**Comment by alecmuffett** [comment]
I can confirm that "pip install --upgrade pip" is not actually helpful because the extant pip in the above is owned by debian, and the upgrade will not overwrite it.

**Comment by alecmuffett** [comment]
therefore:
```
aptitude install python-pip liblzma-dev
pip install carml service_identity
{fix broken permissions in /usr/local}
```

**Comment by meejah** [comment]
There were some problems with the setup instructions, but not really the same as above. I've fixed them and tested on a fresh Debian VM: https://carml.readthedocs.io/en/latest/installation.html

**Comment by meejah** [comment]
Should be better in latest release, with improved instructions
